config/routes.rb
Rails.application.routes.draw do
  
  resources :users

  root 'users#index'

  get '/landing', to: "users#landing"

  get '/validate', to: "users#validate"

  post '/validate', to: "users#validate"

  get '/display', to: "users#display"

  post '/display', to: "users#display"

  get '/logout', to: "users#logout"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

	validates :username, presence: true
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
	validates :password, presence:true
	#format: { with: /\A(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[[:^alnum:]])/x }

	after_save :addFullname

	def addFullname
		User.where(username: self.username, surname: self.surname).update_all(fullname: self.username+" "+self.surname)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	#require_relative '../modules/testmodule'
	#include TestModule

    before_action :checkSession, :only => [:display, :show]

	def index
	end

	def landing
		session[:user_id] = nil
		session[:last_visited_path] = nil
		@user = User.new
	end

	def display
		@users = User.all
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			ExampleMailer.sample_email(@user).deliver_now
			redirect_to users_path
		else
			render 'new'
		end
	end

	def validate
		if session[:user_id] == nil	
			xname = params[:user][:username]
			xpass = params[:user][:password]
			@user = Methods.new.crossCheck(xname, xpass).first
		end
		if @user.present?
			session[:user_id] = @user.id
			session[:last_visited_path] = request.original_url
			#redirect_to 'display_path'
			render 'display'
		else
			if session[:user_id] == nil
				flash[:danger] = "....."
				redirect_to landing_path
			else
				@user = User.where(id: session[:user_id]).select("*").first
				render 'display'
			end
		end
	end

	def display
		#format.html { redirect_to(display_path) }
	end

	def logout
		session[:user_id] = nil
		session[:last_visited_path] = nil   
    	redirect_to users_path, notice: 'Logged out!' 
	end

	

	private

  		def user_params
    		params.require(:user).permit(:username, :surname, :password, :email, :role)
 		end

 		def checkSession			
			if session[:user_id].present?
				redirect_to session[:last_visited_path]
			else
				redirect_to landing_path
			end
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>First</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/display.html.erb
<h2><%= @user.username %> is a <%= @user.role %>
</h2>
<br><br>
<%= link_to "Log Out", logout_path %> 

app/views/users/index.html.erb
<p>
<%= link_to "Log In", landing_path %> 
</p>

app/views/users/landing.html.erb
<h1>Welcome to Goomo-Flights</h1>

<%= form_for @user, :url => { :action => 'validate'} do |form| %>

  <p>
    <%= form.label :UserName %><br>
    <%= form.text_field :username %>
  </p>
 
  <p>
    <%= form.label :Password %><br>
    <%= form.password_field :password %>
  </p>
 
  <p>
    <%= form.submit "Log In" %>
  </p>
 
<% end %>

<%= link_to 'Sign Up', new_user_path %>

<br>
<% if flash[:danger] %>
  <div style="color:red" ><%= flash[:danger] %></div>
<% end %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
<div class="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prevented this record from being saved:</h2>
  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

<%= form_with model: @user, local: true do |form| %>
  
  <h2>Create your profile</h2>
  <br>

  <p>
    <%= form.label :UserName %><br>
    <%= form.text_field :username %>
  </p>

  <p>
    <%= form.label :SurName %><br>
    <%= form.text_field :surname %>
  </p>

  <p>
    <%= form.label :Email %><br>
    <%= form.text_field :email %>
  </p>
 
  <p>
    <%= form.label :Password %><br>
    <%= form.password_field :password %>
  </p>
  <p>
    <%= form.label :Role %><br>
    <%= form.text_field :role %>
  </p> 
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>